# apiVersion: karpenter.sh/v1
# kind: NodePool
# metadata:
#   name: default
# spec:
#   disruption:
#     budgets:
#     - nodes: 10%
#     consolidateAfter: 0s
#     consolidationPolicy: WhenEmptyOrUnderutilized
#   limits:
#     cpu: 1k
#   template:
#     spec:
#       expireAfter: 72h0m0s
#       nodeClassRef:
#         group: karpenter.k8s.aws
#         kind: EC2NodeClass
#         name: default
#       requirements:
#       - key: karpenter.k8s.aws/instance-category
#         operator: In
#         values:
#         - c
#         - m
#         - r
#       - key: karpenter.k8s.aws/instance-cpu
#         operator: In
#         values:
#         - "4"
#         - "8"
#         - "16"
#       - key: karpenter.k8s.aws/instance-hypervisor
#         operator: In
#         values:
#         - nitro
#       - key: topology.kubernetes.io/zone
#         operator: In
#         values:
#         - ap-southeast-1a
#         - ap-southeast-1b
#         - ap-southeast-1c
#       - key: kubernetes.io/arch
#         operator: In
#         values:
#         - amd64
#       - key: karpenter.sh/capacity-type
#         operator: In
#         values:
#         - spot
#         - on-demand

# ---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  # amiFamily: AL2023
  amiSelectorTerms:
  # - alias: bottlerocket@latest
  - alias: al2023@latest
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  role: karpenter-ipv4-prefix-delegation-20231126010741917100000005
  securityGroupSelectorTerms:
  - tags:
      Name: ipv4-prefix-delegation-node
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: ipv4-prefix-delegation
  tags:
    karpenter.sh/discovery: ipv4-prefix-delegation
