# apiVersion: v1
# data:
#   cwagentconfig.json: |
#     {
#       "logs": {
#         "metrics_collected": {
#           "kubernetes": {
#             "cluster_name": "ipv4-prefix-delegation",
#             "metrics_collection_interval": 60
#           }
#         },
#         "force_flush_interval": 5
#       },
#       "metrics": {
#           "append_dimensions": {
#             "InstanceId": "${aws:InstanceId}"
#           },
#           "metrics_collected": {
#             "ethtool": {
#               "interface_include": [
#                 "eth0"
#               ],
#               "metrics_include": [
#                 "rx_packets",
#                 "tx_packets",
#                 "bw_in_allowance_exceeded",
#                 "bw_out_allowance_exceeded",
#                 "conntrack_allowance_exceeded",
#                 "linklocal_allowance_exceeded",
#                 "pps_allowance_exceeded"
#               ]
#             }
#         }
#       }
#     }
# kind: ConfigMap
# metadata:
#   annotations:
#     meta.helm.sh/release-name: aws-cloudwatch-metrics
#     meta.helm.sh/release-namespace: amazon-cloudwatch
#   labels:
#     app.kubernetes.io/managed-by: Helm
#     app.kubernetes.io/name: aws-cloudwatch-metrics
#     app.kubernetes.io/version: "1.247350"
#     helm.sh/chart: aws-cloudwatch-metrics-0.0.9
#   name: aws-cloudwatch-metrics
#   namespace: amazon-cloudwatch

---
apiVersion: v1
data:
  cwagentconfig.json: |
    {
      "logs": {
        "metrics_collected": {
          "kubernetes": {
            "cluster_name": "ipv4-prefix-delegation",
            "metrics_collection_interval": 60
          }
        },
        "force_flush_interval": 5
      }
    }
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: aws-cloudwatch-metrics
    meta.helm.sh/release-namespace: amazon-cloudwatch
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: aws-cloudwatch-metrics
    app.kubernetes.io/version: "1.247350"
    helm.sh/chart: aws-cloudwatch-metrics-0.0.9
  name: aws-cloudwatch-metrics
  namespace: amazon-cloudwatch
