apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config-override
  namespace: monitoring
spec:
    route:
      groupWait: 30s
      groupInterval: 5m
      repeatInterval: 12h
      receiver: 'slack'
      routes:
      - receiver: 'slack'
        matchers:
        - name: alertname
          matchType: '=~'
          value: "InfoInhibitor|Watchdog"
    receivers:
    - name: 'slack'
      slackConfigs:
      - apiURL: https://hooks.slack.com/services/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
        title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
        channel: '#webhook-alerts'


        # title: '{{ .Status }} ({{ .Alerts.Firing | len }}): {{ .GroupLabels.SortedPairs.Values | join " " }}'
        # text: '<!channel> {{ .CommonAnnotations.summary }}'
#   #   - name: 'slack-notifications'
#   #     slack_configs:
#   #     - channel: '#webhook-alerts'
        # title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        # text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
#   #       # text: "<!channel> \nsummary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"
